namespace NahidaImpact.Enums.Player;

public enum OpenStateCondType
{
    OPEN_STATE_COND_NONE,
    OPEN_STATE_COND_PARENT_QUEST,
    OPEN_STATE_COND_QUEST,
    OPEN_STATE_COND_PLAYER_LEVEL,
    OPEN_STATE_OFFERING_LEVEL,
    OPEN_STATE_CITY_REPUTATION_LEVEL,
    OPEN_STATE_COND_GCG_LEVEL,
    OPEN_STATE_TRIBAL_REPUTATION_FINISH_NUM,
    OPEN_STATE_COND_PLAYER_BEYOND_LEVEL
}
